version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./nuxt
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
