name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Debugging untuk melihat struktur direktori
      - name: List project files
        run: ls -R
      # Install Node.js dan dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # Check standar penulisan kode (Linting) untuk Nuxt
      - name: Install dependencies & Lint Nuxt
        run: |
          cd nuxt
          npm install
          npm run lint
      # Build Nuxt menjadi static files
      - name: Build Nuxt
        run: |
          cd nuxt
          npm run build
      # Install Go
      - name: Install Go
        run: sudo apt-get install -y golang-go
      # Check standar penulisan kode (Linting) untuk Go
      - name: Lint Go code
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./backend/...
      # Build backend menjadi binary
      - name: Build Go Backend
        run: |
          cd backend
          go build -o mybackend main.go
      # Simpan binary sebagai artifacts (Opsional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: backend/mybackend
